[[agents]]
id = 'alice'
name = 'Alice'
keystore_file = 'alice.key'
public_address = 'HcScio4B7gnUoo9nvis34WVUveP4Hjy8cp8IiGf8Ynwvt9xnVB9CcRn4zYtybpz'
test_agent = true

[[dnas]]
file = 'dist/cc_tuts.dna.json'
hash = 'QmVEtRXBasijzWZR7bpGPn5sNMtkWYWqa3e4jmbvGvje28'
id = 'hc-run-dna'

[[instances]]
agent = 'alice'
dna = 'hc-run-dna'
id = 'test-instance'

[instances.storage]
type = 'memory'

[[interfaces]]
admin = true
id = 'websocket-interface'

[[interfaces.instances]]
id = 'test-instance'

[interfaces.driver]
port = 3401
type = 'websocket'

[network]
type = 'sim2h'
sim2h_url = 'wss://sim2h.holochain.org:9000'